ARG PRODUCT_REGISTRY=harbor.gnapi.tech/iqgeo
ARG PRODUCT_REPOSITORY_PREFIX=releases_

# START SECTION Aliases for Injector images
FROM ${PRODUCT_REGISTRY}/${PRODUCT_REPOSITORY_PREFIX}comms/comms:3.5 AS comms
FROM ${PRODUCT_REGISTRY}/${PRODUCT_REPOSITORY_PREFIX}platform/groups:1.0.2 AS groups
FROM ${PRODUCT_REGISTRY}/${PRODUCT_REPOSITORY_PREFIX}workflow_manager/workflow_manager:4.1.4 AS workflow_manager
# END SECTION

# Create container for building the project
FROM ${PRODUCT_REGISTRY}/${PRODUCT_REPOSITORY_PREFIX}platform/platform-build:7.4

# START SECTION Copy the modules - if you edit these lines manually note that your change will get lost if you run the IQGeo Project Update tool
COPY --link custom ${MODULES}/custom
COPY --from=comms / ${MODULES}/
COPY --from=groups / ${MODULES}/
COPY --from=workflow_manager / ${MODULES}/
# END SECTION

# START CUSTOM SECTION
# END CUSTOM SECTION

# Give www-data user ownership of the modules
RUN chown -R www-data:www-data ${MODULES}

# Fetch pip packages
# --include options are: memcached, redis, ldap, oidc, saml
RUN myw_product fetch pip_packages 

# Fetch node_modules and build all
RUN myw_product fetch node_modules \
    && myw_product build all \
    # Remove dev dependencies from npm files - not needed for production and entries in package-lock.json can cause false positives in security scans
    # ignore if this fails since the parameter is not available in 
    && if myw_product clear --help 2>/dev/null | grep -qE 'npm_manifests'; then \
    myw_product clear npm_manifests; \
    # Remove node_modules - save image size since these are not needed at runtime
    myw_product clear node_modules; \
    fi